export function createGetMockSearchResultResponse(): IPartialSearchResult {
  return {
    songId: 0,
    artistId: 0,
    title: 'You are the best',
    artist: 'Thanks for using this app',
    source: ''
  };
}

export const mockSongsYouWillReceive = [
  'Tornado of Souls',
  'Holy Wars... The Punishment Due',
  'Symphony Of Destruction',
  'Peace Sells',
  'In My Darkest Hour',
  'Hangar 18',
  'Angry Again',
  'Sweating Bullets',
  'Trust',
  'A Tout Le Monde',
  'Wake Up Dead',
  'Lucretia',
  'She-Wolf',
  'Five Magics',
  'Rust In Peace... Polaris',
  'Take No Prisoners',
  'Conquer Or Die',
  'Countdown To Extinction',
  'Dread And The Fugitive Mind',
  'Poison Was The Cure',
  'The Conjuring',
  'Addicted To Chaos',
  'Killing Is My Business... And Business Is Good!',
  'Good Mourning/Black Friday',
  'Mechanix',
  'Last Rites / Loved To Death',
  'Dystopia',
  "Skin O' My Teeth",
  'Devils Island',
  'This Was My Life',
  'The Killing Road',
  'The Sick, The Dying... And The Dead!',
  'Set The World Afire',
  'Into The Lungs Of Hell',
  'Ashes In Your Mouth',
  'Duke Nukem Theme',
  'Dawn Patrol',
  "We'll Be Back",
  'Hanger 18',
  'Family Tree',
  'Hook In Mouth',
  'Poisonous Shadows',
  'Conquer Or Die (E standard)',
  'High Speed Dirt',
  'Disconnect',
  'Blood Of Heroes',
  'Bad Omen',
  'Train Of Consequences',
  'Reckoning Day',
  'My Last Words'
];
